# Generated by Django 2.2 on 2019-04-01 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=60)),
                ('crawling_date', models.DateTimeField(auto_now_add=True)),
                ('post_id', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('school_name', models.CharField(max_length=60)),
                ('category', models.CharField(choices=[('n', 'notice'), ('p', 'parents_notice')], max_length=1)),
                ('post_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FileBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=60)),
                ('crawling_date', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='download_files')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_board', to='boards.Board')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
