# Generated by Django 2.2 on 2019-04-03 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20190403_1908'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ('-post_date',)},
        ),
    ]
